// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVZACEG_fqLkE28W-1j_bNb0Q9IMEyjBg',
    appId: '1:614152838105:web:646f4857738dfd7e0e57c8',
    messagingSenderId: '614152838105',
    projectId: 'community-beat-4b79a',
    authDomain: 'community-beat-4b79a.firebaseapp.com',
    storageBucket: 'community-beat-4b79a.firebasestorage.app',
    measurementId: 'G-0ZTX1NWH7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN5SuYNkD3gK3tfHBRaAUSjfk2OWYuJ7E',
    appId: '1:614152838105:android:dfa176bb775857d50e57c8',
    messagingSenderId: '614152838105',
    projectId: 'community-beat-4b79a',
    storageBucket: 'community-beat-4b79a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGL3K3G5XZKDh1LDyEnjz6b--zBXsZy1s',
    appId: '1:614152838105:ios:c13d31d7ae6ea9460e57c8',
    messagingSenderId: '614152838105',
    projectId: 'community-beat-4b79a',
    storageBucket: 'community-beat-4b79a.firebasestorage.app',
    iosClientId: '614152838105-il6gi05davbam0k85e7o10e7n3lbds2i.apps.googleusercontent.com',
    iosBundleId: 'com.wordnerd.communitybeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGL3K3G5XZKDh1LDyEnjz6b--zBXsZy1s',
    appId: '1:614152838105:ios:c351473c6be3bea00e57c8',
    messagingSenderId: '614152838105',
    projectId: 'community-beat-4b79a',
    storageBucket: 'community-beat-4b79a.firebasestorage.app',
    iosClientId: '614152838105-rgfq95oqdj2lrkntma27mm7t6cdf3eh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.communityBeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVZACEG_fqLkE28W-1j_bNb0Q9IMEyjBg',
    appId: '1:614152838105:web:2d8e33eda37361140e57c8',
    messagingSenderId: '614152838105',
    projectId: 'community-beat-4b79a',
    authDomain: 'community-beat-4b79a.firebaseapp.com',
    storageBucket: 'community-beat-4b79a.firebasestorage.app',
    measurementId: 'G-RZRKEW1Q7J',
  );

}